all:
  children:
    swarmmanagers:
      hosts:
        swarm-manager:
          ansible_user: billyderby22
          ansible_ssh_private_key_file: /home/billyderby97/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    swarmworkers:
      hosts:
        swarm-worker:
          ansible_user: billyderby22
          ansible_ssh_private_key_file: /home/billyderby97/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ciservers:
      hosts:
        jenkins:
          ansible_user: billyderby22
          ansible_ssh_private_key_file: /home/billyderby97/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    devvm:
      hosts:
        dev:
          ansible_user: billyderby22
          ansible_ssh_private_key_file: /home/billyderby97/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'